# Q1.Questions on Basic NumPy Array

In [7]:
# Q1. a) reverse
import numpy as np

arr = np.array([1,2,3,4,5,6])
np.flip(arr)

arr

array([1, 2, 3, 4, 5, 6])

In [17]:
# b) flatten
arr = np.array([[1,2,3],[2,4,5],[1,2,3]])
arr = arr.flatten('F') # col major flatten operation
arr

array([1, 2, 1, 2, 4, 2, 3, 5, 3])

In [20]:
arr.reshape(-1)

array([1, 2, 1, 2, 4, 2, 3, 5, 3])

In [26]:
#Q1 c)
arr1 = np.array([[1,2],[3,4]])
arr2 = np.array([[1,2],[3,4]])

np.equal(arr2,arr1)
np.array_equal(arr2,arr1)

True

In [35]:
# Q1 d)
x = np.array([1,2,3,4,5,1,2,1,1,1,6,6,])
# find most frequent value
x1 = np.bincount(x)
x1 # found the most occurent element

# for i in range(len(x)):
#     if x[i] == x1:
#         print(i)

array([0, 5, 2, 1, 1, 1, 2], dtype=int64)

In [40]:
# e)
m = np.matrix('[4,1,9; 12,3,1; 4,5,6]')

print(np.sum(m))
print(np.sum(m,axis= 0))  # col sum
print(np.sum(m,axis= 1))  # row sum

45
[[20  9 16]]
[[14]
 [16]
 [15]]


In [53]:
# f)
n_array = np.array([[55,25,15],[30,44,2],[11,45,77]])
print(np.diag(n_array).sum())
eigenvalues, eigenvectors = np.linalg.eig(n_array)
print(eigenvalues)
print(eigenvectors)
print(np.linalg.inv(n_array))
print(np.linalg.det(n_array))

176
[98.16835147 28.097044   49.73460452]
[[ 0.4574917   0.34637121 -0.15017693]
 [ 0.28447814 -0.72784061 -0.4852124 ]
 [ 0.84248058  0.59184038  0.8614034 ]]
[[ 0.02404141 -0.00911212 -0.00444671]
 [-0.01667882  0.02966905  0.0024785 ]
 [ 0.00631287 -0.01603732  0.01217379]]
137180.0000000001


In [69]:
# g)
p = np.matrix('[1,2;2,3]')
q = np.matrix('[4,5;6,7]')

p = np.array([[1,2],[2,3]])
q = np.array([[4,5],[6,7]])

# we will first need to flatten the arrays first
p.flatten()
q.flatten()

r = p@q
r
print(np.cov(p,q)[0,1])

0.5


In [75]:
p = np.array([[1, 2], [2, 3], [4, 5]])
q = np.array([[4, 5, 1], [6, 7, 2]])


r = p@q
print(r)

# p.flatten()
# q.flatten()
print(np.cov(p,q.T))


[[16 19  5]
 [26 31  8]
 [46 55 14]]
[[0.5 0.5 0.5 1.  1.  0.5]
 [0.5 0.5 0.5 1.  1.  0.5]
 [0.5 0.5 0.5 1.  1.  0.5]
 [1.  1.  1.  2.  2.  1. ]
 [1.  1.  1.  2.  2.  1. ]
 [0.5 0.5 0.5 1.  1.  0.5]]


In [ ]:
x = np.array([[2, 3, 4], [3, 2, 9]])
y = np.array([[1, 5, 0], [5, 10, 3]])
print(np.inner(x,y))
print(np.outer(x,y))
print(np.array(np.array(np.meshgrid(x,y))).T.reshape(-1,2))

# Q2 Based on NumPy Mathematics and Statistics 

In [ ]:
# a)
arr = np.array([[1, -2, 3],[-4, 5, -6]])
arr.__abs__()
print(np.percentile(arr,75))
print(np.percentile(arr,50))
print(np.percentile(arr,25))

print(np.mean(arr))
print(np.median (arr))
print(np.std(arr))

2.5
-0.5
-3.5
-0.5
-0.5
3.8622100754188224


In [ ]:
# b)
a = np.array([-1.8, -1.6, -0.5, 0.5,1.6, 1.8, 3.0])
print(np.floor(a))
print(np.ceil(a))
print(np.trunc(a))
print(np.round(a,))

[-2. -2. -1.  0.  1.  1.  3.]
[-1. -1. -0.  1.  2.  2.  3.]
[-1. -1. -0.  0.  1.  1.  3.]
[-2. -2. -0.  0.  2.  2.  3.]


# Q3: Based on Searching and Sorting

In [106]:
array = np.array([10, 52, 62, 16, 16, 54, 453])
np.sort(array)
np.sort(array)[0:4]
np.sort(array)[6:1:-1]

array([453,  62,  54,  52,  16])

In [109]:
array = np.array([1.0, 1.2, 2.2, 2.0, 3.0, 2.0])
for i in array:
    if int(i) == i:
        print(i)
print('\n')
for i in array:
    if int(i) != i:
        print(i)

1.0
2.0
3.0
2.0


1.2
2.2


# Q4

In [111]:
pip install cv2

Note: you may need to restart the kernel to use updated packages.


ERROR: Could not find a version that satisfies the requirement cv2 (from versions: none)
ERROR: No matching distribution found for cv2

[notice] A new release of pip is available: 24.0 -> 25.1.1
[notice] To update, run: python.exe -m pip install --upgrade pip


In [112]:
import cv2  # OpenCV

def img_to_array(path):
    # Read image using OpenCV
    img = cv2.imread(path, cv2.IMREAD_UNCHANGED)

    if img is None:
        raise FileNotFoundError("Image not found or path incorrect.")

    # Check number of channels
    if len(img.shape) == 2:
        # Grayscale image
        print("Grayscale image detected.")
        np.savetxt("grayscale_image.txt", img, fmt='%d')
    elif len(img.shape) == 3:
        # RGB image: OpenCV reads as BGR by default
        print("RGB image detected.")
        img_rgb = cv2.cvtColor(img, cv2.COLOR_BGR2RGB)
        # Save as a 3D array in .npy format
        np.save("rgb_image.npy", img_rgb)
    else:
        print("Unsupported image format.")

    return img

ModuleNotFoundError: No module named 'cv2'